### ISSUE TITLE
menuBar fixes

### ISSUE THREAD

**Issue by JoshuaCrotts** [JoshuaCrotts/Logic-Learning-Assistance-Tool#70]
In the menubar branch:

- "Advance" should probably be "Advanced"
- The language drop-down should be sorted.
- I feel like there's a lot of empty space in these menus... perhaps it could be condensed somehow?
- We should center this dialog box.

**Comment by CodingTheories** [comment]
I'm not sure what do you mean by "We should center this dialog box."

**Comment by CodingTheories** [comment]
done
