### ISSUE TITLE
Labels that is not been translated

### ISSUE THREAD

**Issue by CodingTheories** [JoshuaCrotts/Logic-Learning-Assistance-Tool#83]
There are new labels that been added lately. As a result, they are not been included to the UIObject and connected to the translation API.

pictures to show where is the problem at:
1. Algorithms ComboBox
![pic 1](https://i.ibb.co/cwZ8PyD/1.png)
2. Export Menubar
![pic 1](https://i.ibb.co/mJKn7Tt/2.png)

**Comment by JoshuaCrotts** [comment]
Closed for now due to temporary hold on development.
